server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://114.55.145.3:3306/mangostreet_test1
    username: root
    password: wjyy26303
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true